Fix org:sim Benchmark.ms caused NameError
- Bug introduced in the Rails 8.1 upgrade
  - 8eff7a2
  - https://guides.rubyonrails.org/8_1_release_notes.html#active-support-removals
- Fix suggested in https://nithinbekal.com/posts/rails-benchmark-ms-deprecated/
```
NameError: uninitialized constant Seed::Benchmark (NameError)

    elapsed_time_ms = Benchmark.ms(&block)
                      ^^^^^^^^^
/rails/app/models/seed.rb:176:in 'Seed#benchmark'
/rails/app/models/seed.rb:79:in 'Seed#create_random_seeds'
/rails/lib/tasks/org.rake:57:in 'block (2 levels) in <main>'
Tasks: TOP => org:sim => org:simulation
```